mba.raw <- readLines("6_groceries.dat")
head(mba.raw)
summary(mba.raw)
mba.list <- strsplit(mba.raw, ",")
names(mba.list) <- paste("Trans", 1:length(mba.list))
str(mba.list)
library(car)
some(mba.list)
rm(mba.raw)
install.packages("arulesViz")
library("arules")
mba.trans <- as(mba.list, "transactions")
summary(mba.trans)
head(mba.trans)
#mba analysis
#finding rules
mba.rules <- apriori(mba.trans, parameter = list(supp=0.01, conf=0.3, target="rules"))
inspect(subset(mba.rules, lift > 3))
library(arulesViz)
library(plotly)
plot(mba.rules, engine = "plotly")
#extracting 15 rules with highest lifts
groc.lift <- head(sort(mba.rules, by="lift"), 15)
inspect(groc.lift)
plot(groc.lift, method="graph")